apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clep

resources:
  - nats.yaml
  - postgres.yaml
  - gateway.yaml
  - hermes-adapter.yaml

namespace: clep

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: clep
      app.kubernetes.io/managed-by: flux

patches:
  - target:
      kind: Deployment
      name: clep-gateway
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ezzops/clep-gateway:0.1.0

  - target:
      kind: Deployment
      name: hermes-adapter
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ezzops/clep-gateway:0.1.0
